logging:
  level: INFO
  path: ./outputs/logs

paths:
## INPUTS
  features: ./outputs/features
  tokenized: ./outputs/tokenized
  cohort: ./outputs/cohort_absolute  # path to cohort directory
  outcomes: ./outputs/outcomes
  outcome: TEST_OUTCOME.csv

  # tokenized_file: ...
  # tokenized_pids: ...
  
## OUTPUTS
  prepared_data: ./outputs/oot_all/processed_data/ # Save model/outputs to this folder
  #runs: ./outputs/pretraining # Use for generating a new model folder

data:
  type: "test"
  test_modes: ["train", "tuning", "held_out"] # list with name of features where test data is stored. Only used for test_data
  min_len: 1
  truncation_len: 20
  
outcome: # we will convert outcomes to binary based on whether at least one outcome is in the follow up window
  n_hours_censoring: 0 # censor time after index date (negative means before)
  n_hours_start_follow_up: 1 # start follow up (considering outcomes) time after index date (negative means before)
  n_hours_end_follow_up: 8500 # end follow up (considering outcomes) time after index date (negative means before)
