logging:
  level: INFO
  path: ./outputs/logs

paths:
  ### Inputs
  features: ./outputs/features
  initial_pids: ./outputs/tokenized/pids_tuning.pt # Initial patients to select from [list of pids] (optional)
  outcomes: ./outputs/outcomes/
  exposure: TEST_CENSOR.csv # Exposure, optional, set to outcome if not provided. For multiple exposures, create a joint exposure file.
  outcome: TEST_OUTCOME.csv # Outcome
  # exclude_pids: # optional, if provided, exclude these pids from the cohort
  # predefined_folds: ./outputs/cohort/finetune/folds.pt # optional, if provided, we will use the folds from the predefined folds file
  
  ### Outputs
  cohort: ./outputs/cohort/finetune_v3/ # Data directory



selection:
  exclude_prior_outcomes: true # Exclude patients who had the outcome before index date
  exposed_only: false # Exclude patients who are not exposed
  age:
    min_years: 18 # Minimum age to include (inclusive)
    max_years: 120 # Maximum age to include (inclusive)
  categories: # here we can include OR exclude categories
    GENDER: # column name in the data
      include: [M] # include only M/ exclude keyword can be used as well.

index_date: # if not provided we can use exposures to get the index dates
  mode: relative # absolute or relative (to exposure)
  absolute: 
    year: 2015
    month: 1
    day: 26
  relative: # takes first exposure as index date
    n_hours_from_exposure: -24 # negative means before exposure, 0 by default

cv_folds: 3 # can be set to 1 if only a simple train/val split is needed
cv_test: false # if true, we will add a test set to the folds
val_ratio: 0.2 # only used if cv_folds is set to 1 and cv_test is false
test_ratio: 0.1 # can be set to 1 for test set creation only (separate from folds)
